### ISSUE TITLE
List styling

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#106]
Unordered lists on the About page appear without bullets.

<img width="628" alt="screenshot 2017-03-17 00 48 48" src="https://cloud.githubusercontent.com/assets/102694/24033719/846e27e2-0aab-11e7-9ff3-d96494229022.png">

**Comment by heymonkeyriot** [comment]
_Mea colpa_. Have just push #107 that will fix this.

It also impacted ordered lists as it was the `li` that was being incorrectly changed. Sorry, should have tested the form page PR more fully.
