### ISSUE TITLE
Verify that all included images are actually used somewhere

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#114]
via `.get_usage()`

Either use the unused images or remove them.

**Comment by shacker** [comment]
Push to master on shacker fork ensures all images are in use - adding some that were unused into blog posts, and deleting others. Size of `original_images` dir is now under 6MBs.  For posterity, here's how I did it:

1) Find all image referenced in explicit relations:

```
from wagtail.wagtailimages.models import Image
imgs = Image.objects.all()
for i in imgs:
  print(i.id, i, i.get_usage())
```

this generates output like this: 

```
Male icon <QuerySet []>
Breads 1 <QuerySet [<Page: Welcome to the Wagtail Bakery!>, <Page: Breads>]>
Breads 2 <QuerySet [<Page: Locations>]>
Breads 3 <QuerySet [<Page: Blog>]>
Breads 4 <QuerySet []>
Female 2 <QuerySet []>
```

delete from list all that have non-empty querysets. 

2) `get_usage()` doesn't account for images in StreamFields. Find these via dumps with greps on the image ID:

```
./manage.py dumpdata --indent 2 --format xml base blog breads locations | grep "\"image\": 38"
```

(yaml because the json output included quotes that were difficult to escape). 

If no output, either delete the image via the admin, or include it in a post.

**Comment by itekhi** [comment]
@shacker Oh man, this is exactly my problem now, ran `.get_usage()` on `Image`s in shell, lots of them are not used, but I'm sure they are used in `StreamField`s. I have 60gbs of just Images 😆 
Could you please show some example code that could do that in bulk?(I can't even find if it's possible to run dumpdata from python)

P.S. Maybe it's an idea for a management command?

**Comment by zerolab** [comment]
Hey all,

This is not a trivial thing to solve. #4702 (original #4481) attempts to do it, but it is some way away.
The PR should have enough to allow you to write your own management command though

**Comment by itekhi** [comment]
@zerolab Thanks a lot! And thank you for your hard work! I see you often in PRs and release logs))

**Comment by zerolab** [comment]
Oops, the PR number had a leading 7. Updated!

(Also, thank you)
