### ISSUE TITLE
Add body content to Locations

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#124]
@heymonkeyriot You had ideas for real content on these pages, yes? Body fields are present on Location now - feel free to add or ask me to add dummy content.

**Comment by heymonkeyriot** [comment]
I'm closing this as I think this is resolved by commit [645b6a](https://github.com/shacker/bakerydemo/commit/645b6a7f854d593862888e9c18f6b678fcdc4bc4) on the fork that you created @shacker
