### ISSUE TITLE
Dummy people

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#13]

**Comment by shacker** [comment]
I've got three dummy people in and am ready to close this, but @heymonkeyriot I see you put a 'design' tag on this - what design work is needed? Are we going to have People pages?

**Comment by heymonkeyriot** [comment]
Have removed the tag. Because you're right, there's no plan at the moment to have a people page, and we'll be exposing them via the blog etc. Sorry!

**Comment by shacker** [comment]
Cool, thanks. My dummy people are named after (dead) blues musicians, male and female.
