### ISSUE TITLE
Dummy blog posts

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#14]

**Comment by shacker** [comment]
Five blog posts now in, cribbed from wikipedia content, with bylines, pub dates, intros, etc.

**Comment by tomdyson** [comment]
Where are they, @shacker?

**Comment by shacker** [comment]
@tomdyson Because authors, posts, images, content types are all interrelated, and because I don't want people to have to keep wiping and recreating dbs during dev, I'm packaging all the content and images and will release it as a package with a loader. Getting close...

**Comment by tomdyson** [comment]
@shacker understood, thanks for the explanation!
