### ISSUE TITLE
preview bug with routablePage

### ISSUE THREAD

**Issue by zr777** [wagtail/bakerydemo#142]
Page not found (404)
Request Method:	POST
Request URL:	http://localhost:8000/admin/pages/61/edit/preview/
Raised by:	wagtail.wagtailadmin.views.pages.preview_on_edit
Using the URLconf defined in bakerydemo.urls, Django tried these URL patterns, in this order:
^tags/(\w+)/$ [name='tag_archive']
^tags/$ [name='tag_archive']
The current URL, , didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by shacker** [comment]
Thanks for the report. Can you let us know what page (or type of page) you were editing when you clicked Preview and got this 404? Thanks.

**Comment by zr777** [comment]
sorry i forget, but i don't change any code about the demo, the page id is 61, a simple post page, hope it helps

**Comment by shacker** [comment]
Thanks - I've got a PR in for this now.
