### ISSUE TITLE
NotImplementedError: Complex filters with double-underscore clauses are not implemented yet

### ISSUE THREAD

**Issue by abadger1406** [wagtail/bakerydemo#148]
When trying to create a new locations page, I get this error.

**Comment by abadger1406** [comment]
![screenshot from 2017-05-13 23-48-49](https://cloud.githubusercontent.com/assets/634924/26037072/a51558e2-38e3-11e7-81e0-dac62c84aadd.png)

**Comment by daaray** [comment]
Can you do a `pip freeze` and relay what version of `django-modelcluster` you have installed?

**Comment by gasman** [comment]
This is a known limitation of the current version of `django-modelcluster`, which will be fixed by https://github.com/wagtail/django-modelcluster/pull/102.
