### ISSUE TITLE
Contact Form styling

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#15]

**Comment by shacker** [comment]
A demo contact form with these fields has been created and will be in the full data dump. 

Subject
Your Name
Your Email
Purpose [dropdown choices = Comment, Question, Feedback]
Body [textarea]

`EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'`

is already set in base.py and heroku.py to ensure the form does not send live email, and this is noted in the demo form and readme.

Re-assigning to @heymonkeyriot for styling.

**Comment by heymonkeyriot** [comment]
Thanks @shacker 

From doing a very quick play earlier this morning I think Bootstrap does most of the heavy lifting with this, just need to make sure that all the field items are semantically marked up

**Comment by shacker** [comment]
I can take this over if you're too busy. Looks like we'll need to switch from `form.as_p` to rendering the form fields manually in the template to put the correct styling on them.

**Comment by heymonkeyriot** [comment]
Oh, sorry @shacker I missed your comment on here. I'm going to start on this today so that we can get it running; conscious I let it slip slightly.

**Comment by heymonkeyriot** [comment]
I think this can be closed right @shacker? Unless you'd like to keep it open for the work you're doing on the dummy data?

**Comment by shacker** [comment]
Yeppers.
