### ISSUE TITLE
Issues deploying to Heroku

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/bakerydemo#152]
I have managed to get this demo site running locally (in a virtualenv, with SQLite), but am facing a lot of issues trying to deploy it on Heroku.

The issues so far are:

## The Python runtime specified in `runtime.txt` does not work on Heroku.

This can be reproduced by using Heroku's "single-click deploy", https://heroku.com/deploy?template=https://github.com/wagtail/bakerydemo. Error log:

```
-----> Python app detected
-----> Installing python-3.5.0
 !     Requested runtime (python-3.5.0) is not available for this stack (heroku-16).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

I fixed this by cloning the repository, changing the verison to the latest Python 3 defined on Heroku's Python support article, and doing the deployment locally with the Heroku CLI.

## Post-deploy script did not load any data

For reference, from app.json: https://github.com/wagtail/bakerydemo/blob/82b745cd3ed847842d6aa67923d8776e78e77fec/app.json#L11-L13

The first time this ran, it seems to have stopped after the migrations. No data was loaded and the site displayed was empty. Running this exact same command manually (within `heroku run bash`) worked.

This may be because, for reasons I do not understand, the `DJANGO_SETTINGS_MODULE` was not properly loaded. I do remember setting this manually with `heroku config:set` at some stage.

## Served homepage has no `head` tag

This really puzzles me. I have no idea where this could come from, it might just be me destroying my setup with the commands I ran to fix the other issues. Here is the HTML I receive for the homepage, as if everything in `head.html` just wasn't rendered:

```html
  | 
  |  
  |  
  | <body class="template-home-page">
  |  
  |  
  |  
  |  
  |  
  |  
  | <div class="header clearfix" role="banner">
```

**Comment by daaray** [comment]
I have updated `runtime.txt` to Python  3.6.2.  Can you attempt another deploy via the magic button and see if it works for you now?  I was able to successfully deploy a new instance with it.
