### ISSUE TITLE
Page chooser doesn't render chooser UI 

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/bakerydemo#167]
When using the link control in Hallo.js, the link/page chooser modal does not contain any of the UI to pick a Wagtail page.

<img width="716" alt="page-chooser-bakerydemo" src="https://user-images.githubusercontent.com/877585/31722072-0675d0da-b413-11e7-9bf7-02a329af6774.png">

There is a network request fired to http://localhost:8000/admin/choose-page/1/?allow_external_link=true&link_text=Yeasts&allow_email_link=true, which seems to be returning correctly (no errors in the browser console nor in the server's), but no UI appears.

----

- Wagtail 2.0a0
- Default setup of https://github.com/wagtail/vagrant-wagtail-develop

**Comment by heymonkeyriot** [comment]
I wonder if this is a wagtail 2.0 issue. Let me see if I can replicate on an earlier instance of the demo.

**Comment by heymonkeyriot** [comment]
Also fails using Wagtail 1.9.1 and Wagtail 1.8. Curiously if one enters a string to search against it works as expected. I can't think of anything we're doing on the page models that would stop explorer from working 🤔

**Comment by thibaudcolas** [comment]
I can't reproduce anymore. No idea what I've changed though :/

**Comment by gasman** [comment]
This was fixed in #174 - didn't see there was already an issue for it :-)
