### ISSUE TITLE
Delete stray migrations

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/bakerydemo#171]
Some migrations seem to have creeped in to the demo project.

We were trying hard to keep them out to keep the initial build for a user as clean as possible.

Is it worth deleting them? Though I suspect it'll create some migration issues for those users with bakerydemo that have them already. Thoughts?

**Comment by gasman** [comment]
I don't think (lack of) migrations is a meaningful measure of a project's cleanliness... anyone who treats it as such is going to get a nasty shock when they start a real-world project ;-)

As you say, avoiding migrations is going to cause hassle for anyone using the project as more than a throwaway demo (e.g. to develop Wagtail against) - my vote is to not worry about them.

**Comment by heymonkeyriot** [comment]
Yup, all fair. Still feels like a slight shame, but as you say not a big deal :)
