### ISSUE TITLE
Bad behavior when deploying to Docker

### ISSUE THREAD

**Issue by spapas** [wagtail/bakerydemo#186]
I tried installing the wagtail bakery demo (from https://github.com/wagtail/bakerydemo) using Docker on a Centos 7 system. Everything seemed to work ok however there is a strange issue with the images. When I first visit the homepage the images are all missing (return 404 not found)... When I try refreshing that page a couple of times the images start randomly appearing ... after a lot of refreshes all images arte there. However if I do a hard refresh (ctrl+f5) most images disappear again !! 

Please notice that the image and thumbnail files are all there in the /media/images folder (I have connected to the docker container and checked it) the problem is that sometimes these images are not server properly.

**Comment by thibaudcolas** [comment]
This seemed to work fine for me when testing the Docker build as part of #233. I’m on macOS but that’s about the only difference 😕. @spapas let me know if you’re still having the issue with a fresh build and I’ll reopen.
