### ISSUE TITLE
Validation on long lat co-ordinates

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/bakerydemo#19]
Putting in anything other than the expected format for long lat co-ordinate into the editor will give an IndexError `list index out of range` error.

A long lat will normally be something like `64.127146, -21.880038`. Co-ordinates that aren't valid (e.g. `10391293939, -1238929101`) will avoid the error, but putting in `abc` or `123 -123` etc. will create the error.

Regex on the field?

**Comment by shacker** [comment]
Right now we suggest in help text that people copy this string directly from google, then we split it on comma to get separate lat and long. If they follow instructions there should be no problem. It is a required field. It seems a person would have to try hard to get this wrong. Our concern?

**Comment by daaray** [comment]
We definitely want to avoid the site throwing 500 errors, which, without a proper validator, does happen.  I will add it.

**Comment by heymonkeyriot** [comment]
I managed to break it. I like most people think I'm smarter than instructions :)

I think since it's a fairly fatal issue (it throws a 500) we should have some form of validation.

**Comment by shacker** [comment]
Oh true - yeah, no crashers! And I see this is already in - very clean (and instructional) solution. Thanks.
