### ISSUE TITLE
Where is the people page?

### ISSUE THREAD

**Issue by epicserve** [wagtail/bakerydemo#190]
I see there is People model and that you can add a person in the admin, but I'm not seeing how view the people on the actual site.

**Comment by gasman** [comment]
Hi @epicserve - the People model is just used to associate blog pages with authors.

**Comment by epicserve** [comment]
@gasman,

Thanks, I was looking for a way to make a staff page that has a list of staff. I copied that model and made view like this:

```
class PeopleList(generic.TemplateView):
    template_name = 'people/people_list.html'

    def get_context_data(self, **kwargs):
        context = super(PeopleList, self).get_context_data(**kwargs)
        context['people'] = Person.objects.all()
        return context
```

This works, but it would be nice to be able to drag and drop the people to change the order they appear on the page. Any thoughts or suggestions?
