### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by Kuntal-KK** [wagtail/bakerydemo#203]
I am getting this error whenever running pip install -r requirements.txt command. I am using python 3.6.3 and window 10. Can anyone help? Below is the error I am getting
    

> Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\kunta\AppData\Local\Temp\pip-install-35pnypjc\uwsgi\setup.py", line 3, in <module>
>         import uwsgiconfig as uc
>       File "C:\Users\kunta\AppData\Local\Temp\pip-install-35pnypjc\uwsgi\uwsgiconfig.py", line 8, in <module>
>         uwsgi_os = os.uname()[0]
>     AttributeError: module 'os' has no attribute 'uname'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\kunta\AppData\Local\Temp\pip-install-35pnypjc\uwsgi\

**Comment by Kuntal-KK** [comment]
I have solved it. Removed uwsgi from production requirement file.

**Comment by tannerrimes12** [comment]
Same issue, although removing uwsgi did no work for me.
