### ISSUE TITLE
Enable People snippet search?

### ISSUE THREAD

**Issue by paolodina** [wagtail/bakerydemo#205]
Now:
![screenshot_2018-06-02_23-03-51](https://user-images.githubusercontent.com/1157401/40880911-212ba74c-66ba-11e8-8fdd-99c502cf548e.png)

With search:
![screenshot_2018-06-02_23-06-17](https://user-images.githubusercontent.com/1157401/40880914-2b3803b6-66ba-11e8-83a5-3955c79ef4e4.png)

I managed to get the search form changing the snippet definition from
```
class People(ClusterableModel):
```

to
```
class People(index.Indexed, ClusterableModel):
```

but I get these warnings because `index.Indexed` is meant to be used with pages:
```
base.People: People.search_fields contains field 'content_type' but it doesn't exist
base.People: People.search_fields contains field 'depth' but it doesn't exist
base.People: People.search_fields contains field 'first_published_at' but it doesn't exist
base.People: People.search_fields contains field 'last_published_at' but it doesn't exist
base.People: People.search_fields contains field 'latest_revision_created_at' but it doesn't exist
base.People: People.search_fields contains field 'live' but it doesn't exist
base.People: People.search_fields contains field 'locked' but it doesn't exist
base.People: People.search_fields contains field 'owner' but it doesn't exist
base.People: People.search_fields contains field 'path' but it doesn't exist
base.People: People.search_fields contains field 'show_in_menus' but it doesn't exist
base.People: People.search_fields contains field 'title' but it doesn't exist
base.People: People.search_fields contains field 'title' but it doesn't exist
```
Then I wonder if how I added search to People is ok or not, and if not how to do it correctly.

**Comment by gasman** [comment]
`index.Indexed` isn't specific to pages. The problem is this line:

https://github.com/wagtail/bakerydemo/blob/0f11e0f208afd3e724eb8fd3af8f754761eb3cbe/bakerydemo/base/models.py#L59

`search_fields` here should not be extending `Page.search_fields`.
