### ISSUE TITLE
git@github.com: Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by techbeauty** [wagtail/bakerydemo#208]
Hello, I was trying to follow the "Setup with Virtualenv" instructions and kept receiving an error when trying to clone the the repository:

web@ubuntuserver1804:~$ git clone git@github.com:wagtail/bakerydemo.git
Cloning into 'bakerydemo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

OS: Ubuntu 18.04

I was able to finally clone your repository after adding an SSH key to my github account per this issue:
https://github.com/gatsbyjs/gatsby/issues/3713

Based on this, it looks like someone merged an update that broke things for people without a public key.

Could this be fixed please? This really throws new people off from using this demo.

Thank you,
Rebecca

**Comment by simonwangtx** [comment]
Yeah, the same issue I've met. But obviously, you could use _https://github.com/wagtail/bakerydemo.git_ instead.
