### ISSUE TITLE
People snippet broken?

### ISSUE THREAD

**Issue by gabrielwolf** [wagtail/bakerydemo#209]
`first_name` and `last_name` are unfortunately not editable in the backend. So it's not possible to add another person, as well.  

I set up a fresh bakerydemo Docker installation and a fresh bakerydemo virtualenv installation. Same thing. Everything else works fine.

Any help greatly appreciated.

**Comment by gasman** [comment]
Thanks for the report @gabrielwolf! Have fixed this in #210.

**Comment by gabrielwolf** [comment]
Thank you @gasman. Works here as expected.
