### ISSUE TITLE
Static resource bakery.js 404s

### ISSUE THREAD

**Issue by daaray** [wagtail/bakerydemo#21]
`bakery.js` does not exist.  Did it ever?

https://github.com/wagtail/bakerydemo/blob/master/bakerydemo/templates/base.html#L42

<img width="677" alt="screen shot 2017-02-11 at 5 19 15 pm" src="https://cloud.githubusercontent.com/assets/281961/22857940/41c20d88-f07e-11e6-8475-59eb39d2e1c6.png">

**Comment by heymonkeyriot** [comment]
Ack, sorry. that's really bad git practice of me. I was trying to do something "clever" with mobile nav and then realised we should just use what comes out of the box with Bootstrap. Will delete the reference and commit!
