### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install

### ISSUE THREAD

**Issue by tannerrimes12** [wagtail/bakerydemo#211]
When I try to install the requirements.txt i get this error. Does anyone know how to solve it?

**Comment by gasman** [comment]
Please can you paste in the full "Complete output from command python setup.py egg_info:" of the error?

**Comment by tannerrimes12** [comment]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-owbpps6e/l18n/

**Comment by tannerrimes12** [comment]
There was a guy who had an issue with the same command error, but he said he fixed it by editing the requirements/production.txt file. He removed the uwsgi from the file. So I tried to do the same, but still received the error.

**Comment by gasman** [comment]
Is there really nothing else displayed, other than that one line?
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-owbpps6e/l18n/

**Comment by tannerrimes12** [comment]
Here is what is displayed from when its attempting to collect the l18n



Collecting l18n (from wagtail<2.2,>=2.1->-r base.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/1d/a9/c514038919f430a9b748e31be06e3b365b1e4a4c1aa04b3990a9870df38d/l18n-2016.6.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-owbpps6e/l18n/setup.py", line 99, in <module>
        long_description=open(os.path.join('README.rst')).read(),
      File "/home/admin/.virtualenvs/wagtailbakerydemo/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2135: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-owbpps6e/l18n/

**Comment by gasman** [comment]
This is a known issue with the "l18n" package - please see https://groups.google.com/d/msg/wagtail/X5d8CL3DxUs/XPcMUrrYBQAJ for the fix.

**Comment by tannerrimes12** [comment]
Is the fix inside the google discusion or the gitHub link?

**Comment by tannerrimes12** [comment]
I'm sorry i'm kind of new at this. I can't quite find what I need to do to get rid of that error.

**Comment by gasman** [comment]
Try running the command:

    export LC_ALL=en_US.UTF-8

**Comment by tannerrimes12** [comment]
I get export

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

**Comment by gasman** [comment]
Afraid I can't help further, as this is an issue with the l18n package and your operating system rather than an issue with Wagtail - I'd suggest using one of the alternative installation methods listed in https://github.com/wagtail/bakerydemo#installation.

**Comment by tannerrimes12** [comment]
Hey man, thank you so much! I finally got that little snippet of code to not produce an error, and it worked! My step dad who is a professional app developer and uses linux as his base computer, has been trying to help me with this problem for over 6 hours, but he thought it was my build. Since i'm running crouton inside of ChromeOS. Well thank you so much man!
