### ISSUE TITLE
ImportError: No module named dotenv

### ISSUE THREAD

**Issue by officerebel** [wagtail/bakerydemo#213]
I get an error with installment in virtualenv
./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 5, in <module>
    import dotenv
ImportError: No module named dotenv

**Comment by gasman** [comment]
Hi @officerebel,
`dotenv` should have been installed as part of the `pip install -r requirements.txt` step. Were there any errors shown during that step? If you run `pip freeze`, is `django-dotenv` listed in the output?

**Comment by officerebel** [comment]
pip uninstall python-dotenv did the job django had dot env also. But now the project runs and a only see the homepage. Welcome to your new Wagtail site! Not the bakery.

**Comment by gasman** [comment]
Sounds like you've missed the `./manage.py load_initial_data` step.

**Comment by officerebel** [comment]
Great got it running. Now the css seems to be missing. I see no errors in the browser. Do I have to load the styling too? And where can I read more a about what ./manage.py load_initial_data does? And where it gets it data from.
