### ISSUE TITLE
WagtailBakery admin menu item

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#22]
We are surfacing the People snippet under WagtailBakery. But People and the other three snippet models are already present under Snippets. Do we want to move all snippets under WagtailBakery? Or remove that and leave them all under Snippets? (I vote for the latter - it's more standard).

**Comment by heymonkeyriot** [comment]
I think the WagtailBakery admin menu item needs to be changed.

I'd suggest we have:

 - `Bread categories` with `Origin` and `Country` inside it. That can be our example of a ModelAdminGroup.
- `People` with the people snippet as a simple ModelAdmin

But at the same time I'd suggest we also leave them all as Snippets. There's two reasons for that. One it means we can demo to people who've never seen Wagtail before what a Snippet looks like (both in terms of showing the decorator on the model, and how it appears within the admin) Second it allows us to use the SnippetChooserTool, which is more elegant than putting the foreign key in to a FieldPanel
