### ISSUE TITLE
Hi, the command "docker-compose run app /venv/bin/python manage.py load_initial_data" runs with error.

### ISSUE THREAD

**Issue by fyls** [wagtail/bakerydemo#234]
Hi, the command "docker-compose run app /venv/bin/python manage.py load_initial_data" runs with error.
"....
ImportError: Error loading shared library libexpat.so.1: No such file or directory (needed by /usr/local/lib/python3.5/lib-dynload/pyexpat.cpython-35m-x86_64-linux-gnu.so)
"
You should add requrement to Dockerfile 
"expat-dev" into "RUN set -ex \ && apk add --no-cache --virtual .build-deps "

**Comment by johnraz** [comment]
Hello @fyls, could you give my branch a go (#235)?

Building the docker image should work now.

Thanks!

**Comment by kptac** [comment]
@johnraz - updated to 3.7-alpine and added expat-dev, rebuilt, but I get this error when loading initial data:


> docker-compose run app /venv/bin/python manage.py load_initial_data                Starting 
bakerydemo_db_1            ... done                                                                            Starting 
bakerydemo_elasticsearch_1 ... done                                                                            
standard_init_linux.go:207: exec user process caused "no such file or directory"

**Comment by thibaudcolas** [comment]
@kptac this seems to be working for me, sticking with the existing image except for the addition of `expat-dev`.
