### ISSUE TITLE
Show locations on location index with image thumbnails, alphabetically

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#24]

**Comment by heymonkeyriot** [comment]
@shacker are we talking about the location index page here?

e.g. the location index page needs to list all location pages alphabetically and with the thumbnail image of that location?

**Comment by shacker** [comment]
Yes, sorry - was referring only to the Locations index here.

**Comment by heymonkeyriot** [comment]
No worries. I've amended the title to make it a little clearer.

I'll work on the design bit of it today, and try and get it all in a PR for you to review when your back online PST time.
