### ISSUE TITLE
Heroku deployment appears broken?

### ISSUE THREAD

**Issue by easherma** [wagtail/bakerydemo#257]
[odd-bakery-logs-1570827487361.txt](https://github.com/wagtail/bakerydemo/files/3719588/odd-bakery-logs-1570827487361.txt)

**Comment by gasman** [comment]
Have just tried the [one-click deployment](https://github.com/wagtail/bakerydemo#deploy-to-heroku) link, and it claims to have started up successfully, but accessing any page is failing with: "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details." There's nothing meaningful in the logs I get from `heroku logs` though - it just shows migrations completing successfully...

What are the exact steps you took to bring up the site and retrieve the logs?

**Comment by gasman** [comment]
Never mind - I am indeed now seeing the same uWSGI segfault when I have `https://dashboard.heroku.com/apps/<appname>/logs` open while fetching a page in another tab. Thanks for the report!

**Comment by easherma** [comment]
No problem, @gasman! Any idea what might be causing this? I tried a couple things, but I'm less familiar with this repo (we just like to have it deployed to remind of us of how we've deviated from vanilla Wagtail), but I'm happy to help figure out whats going on.
