### ISSUE TITLE
Pillow 4.0.0

### ISSUE THREAD

**Issue by cscheer01** [wagtail/bakerydemo#259]
I'm running the requirements with pip:
`pip install -r requirements/base.txt`

Having the following error when

> The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source.

I'm running on Windows and I had build zlib from source to get Pillow 6.2.0 to install but it doesn't appear to be working for Pillow 4.0.0 which is in base.txt.

What version(s) of Pillow will the demo will support?

**Comment by gasman** [comment]
Hi @cscheer01 - thanks for the report! Yep, the reference to 4.0.0 is definitely out of date - have now updated that to 6.2 in fecf702b65266cd47b133616f12bbc7aac2920e6.
