### ISSUE TITLE
 Internationalization by duplicating the page tree

### ISSUE THREAD

**Issue by ozcanyarimdunya** [wagtail/bakerydemo#264]
I didn't find any useful information or code about  internationalization on wagtail by duplicating the page tree. 

Any plan for adding internationalization ?

**Comment by zerolab** [comment]
Hi @ozcanyarimdunya,

The previous versions on Wagtail docs had a section on internationalisation (e.g. https://docs.wagtail.io/en/v2.6.3/advanced_topics/i18n/duplicate_tree.html) however those were removed as they were stale and incomplete. See https://github.com/wagtail/wagtail/commit/16bf4cac56684401734201c9bf2aa7d9ce583ac3#commitcomment-35950050 for more details

+ you can find blog posts that take you through the process. e.g. https://www.accordbox.com/blog/how-support-multi-language-wagtail-cms/ or https://www.codista.com/en/blog/wagtail-multi-language-and-internationalization/

Internationalization is on the longer term roadmap, however with the three approaches (and 3rd party modules specified in that commit comment) there is no formal decision as to what direction this may go.

Last, but not least, please join the [#support channel in Wagtail Slack](https://github.com/wagtail/wagtail/wiki/Slack) for this type of queries.
