### ISSUE TITLE
Sporadic missing renditions

### ISSUE THREAD

**Issue by Amondale** [wagtail/bakerydemo#271]
According to [this ](https://docs.wagtail.io/en/v2.9.2/advanced_topics/images/renditions.html)Wagtail documentation: 

Rendered versions of original images generated by the Wagtail {% image %} template tag are called “renditions”, and are stored as new image files in the site’s [media]/images directory on the first invocation.

However I currently am getting sporadic 404 errors such as the following:
[13/Jul/2020 19:16:39] "GET /media/images/Bedouins_making_bread.2e16d0ba.fill-285x200-c100.jpg HTTP/1.1" 404 1938
Not Found: /media/images/Bedouins_making_bread.2e16d0ba.fill-285x200-c100.jpg

whilst other images are OK (generate 200 HTML result).

This may be a "newbie" issue, but I wonder why some [original_images] files are correctly  rendered and some aren't?

It appears the load_initial_data django admin routine will populate [original_images], but is there an equivalent command to pre-populate the [media]/images directory and make these 404s go away?

**Comment by Amondale** [comment]
When I modify the /bakerydemo/bakerydemo/settings/base.py as follows the 404 issue goes away?

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'collect_static'),
    os.path.join(PROJECT_DIR, 'media'),
]

If anyone has an idea why this solves the issue, perhaps this can be closed, or the solution added to README.md

**Comment by gasman** [comment]
Without details of your setup or steps to reproduce this issue, it's hard to advise on this. However, given that the `collect_static` directory is coming into play (which would not be applicable to a local instance running `./manage.py runserver` with development settings), my best guess is that you're running in an environment such as Heroku with a non-persistent file system, and the image files are being lost from one deployment to the next. If so, this is addressed in the readme at https://github.com/wagtail/bakerydemo#storing-wagtail-media-files-on-aws-s3.
