### ISSUE TITLE
Default django-cache-url config causes routing issues on Heroku

### ISSUE THREAD

**Issue by kaedroho** [wagtail/bakerydemo#279]
https://github.com/wagtail/bakerydemo/blob/e82c84b6a3c10006cf2e4f07b7a8dcb972ab6731/bakerydemo/settings/production.py#L45

The default is `locmem`, which is problematic for 12 factor apps and causes URLs to break after publishing pages. We should either change the default to "dummy" or remove this app (surprisingly, it has only 1 star on github! https://github.com/epicserve/django-cache-url)

**Comment by thibaudcolas** [comment]
We do not seem to be using `django-cache-url` anymore, so I’ll close this now.
