### ISSUE TITLE
Please consider diversity concerns in the people you portray in your images collection.

### ISSUE THREAD

**Issue by JoanEliot** [wagtail/bakerydemo#281]
Please excuse me, but the people in your images collection are .all. .white. .men. — and they .all. carry the names of African-American blues musicians. Your guys look sharp, and I too wish I could play and sing like Robert Johnson or Howlin Wolf, and live with their vitality, but I found myself feeling a small shock as I glanced over the images and saw only these faces, and then greater shock when I took in the significance of the 'names.' I think you should find a different set of portraits and use a different set of names. Ms. Perception? A. Blinken?

**Comment by tomdyson** [comment]
Hi @JoanEliot, thanks for this. 

The four photos are of the four people who built the bakery demo, over two days at a Wagtail community sprint in Iceland in 2016. IIRC the original idea was to mock up a music site, but they switched to a bakery on the grounds that bread making was one of the most culturally universal activities the team could think of. I guess the names were a hangover from the initial music plan, but reading your comment now makes me realise that we should have thought more carefully about the combined effect of the names and the photos.

**Comment by JoanEliot** [comment]
Appreciate your response, and understand how you got there. Hope that "should have thought..." expresses something like, "will now think... and make appropriate revisions."

**Comment by thibaudcolas** [comment]
I believe the changes in #329 were to help with this so I’ll close now.
