### ISSUE TITLE
Heroku python runtime not found

### ISSUE THREAD

**Issue by BrianXu20** [wagtail/bakerydemo#287]
This appears when I try to deploy it on Heroku (Manually & one-click deployment):

![Screen Shot 2021-02-04 at 1 43 28 PM](https://user-images.githubusercontent.com/73645085/106852906-cd287980-66f3-11eb-9d77-7ede76af9edf.png)

And this is the official Supported runtimes document:
https://devcenter.heroku.com/articles/python-support#supported-runtimes

![Screen Shot 2021-02-04 at 2 15 49 PM](https://user-images.githubusercontent.com/73645085/106853076-14166f00-66f4-11eb-9165-de3e2576bc74.png)

The runtime specified in the runtime.txt is no longer supported by Heroku.

I changed the python runtime from 3.7.6 to 3.7.9 then it worked

**Comment by thibaudcolas** [comment]
Fixed in #288.
