### ISSUE TITLE
inquiry about the license of this project

### ISSUE THREAD

**Issue by wolfpirker** [wagtail/bakerydemo#297]
Hello,

around 2 1/2 years ago I started a wagtail project, and when I developed it, I was quite much orientating and using some code of bakerydemo. I uploaded my project on Github and deployed it as demonstration on Heroku, but I don't use it in any way commercially. Just recently I was asked about the license of the wagtail project I developed. 

I know it would have been a better idea, to ask about the license earlier when I was starting the project. 

Can you please clarify the license of the project? May parts of the projects code be used?  
If not, I would make my wagtail webproject repository private or remove it and also remove the two Heroku deployments.

**Comment by Scotchester** [comment]
Oops! We should probably have a license on this repo, eh?

I am not, by myself, an authoritative voice on this, but I would guess that the license should be the same as [the Wagtail project itself](https://github.com/wagtail/wagtail/blob/main/LICENSE), the BSD 3-Clause "New" or "Revised" License.

As a practical matter, many of the members of this community have liberally borrowed parts of the code in the bakerydemo for many projects. You should have no fear of anyone coming after you for a license violation :)

**Comment by wolfpirker** [comment]
ok that is good to know. Thank you for your reply. 
I will leave that issue open some more days, in case someone else wants to reply.

**Comment by gasman** [comment]
Thanks for raising this, @wolfpirker! Have now added the BSD licence in d3e8caedd728b7770b1bef917a7cb4f157ad20c7.
