### ISSUE TITLE
TUE versus TUES, THU versus THURS

### ISSUE THREAD

**Issue by Amondale** [wagtail/bakerydemo#298]
Here on the Pacific Coast of the USA, I have tried adding a few of our local bakeries in Portland, OR [amondale/bakerydemo_nginx:app] and they stay closed all the time? It seems to be a Docker-specific issue, I changed settings/base.py to the following snippet:

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True

as well as added the following two lines to my Dockerfile:

ARG ARG_TIMEZONE=America/Los_Angeles
ENV ENV_TIMEZONE ${ARG_TIMEZONE}

and also in the Admin Settings, set TZ to America/Los Angeles but it seems everything evals to UTC somewhere in the code; this is from locations/models.py:

`# Determines if the location is currently open. It is timezone naive`

So please explain the use of the word "naive", as I cannot see the true open/closed status of any bakery in my neighborhood.  

Really would be cool if we could figure TZ from Lat/Long, maybe I can scrounge a DB of TZ of all the world's major cities; then I can begin my blog of "Great Bakeries of the Whole World" and we could calculate T or F based on that tablespace. Maybe just scrapping the "Sorry location is closed" text would be the lazy coder's way out of the issue.

TIA,
Alex

**Comment by Amondale** [comment]
<img width="528" alt="lovejoy" src="https://user-images.githubusercontent.com/8033475/129223351-9c17084a-e042-4ff9-b105-dad75d89e2c2.PNG">
<img width="481" alt="models" src="https://user-images.githubusercontent.com/8033475/129223367-58e14baa-ccfc-4fb3-80cd-dbbfeac73934.PNG">
<img width="534" alt="models2" src="https://user-images.githubusercontent.com/8033475/129223383-11c51323-17de-4963-bab9-62389c2ba8a7.PNG">

**Comment by Amondale** [comment]
AHA! This fixed the issue:
[locations/choices.py]
DAY_CHOICES = (
    ('MON', 'Monday'),
    ('TUE', 'Tuesday'),
    ('WED', 'Wednesday'),
    ('THU', 'Thursday'),
    ('FRI', 'Friday'),
    ('SAT', 'Saturday'),
    ('SUN', 'Sunday'),
)

Evidently the use of TUES and THURS versus TUE and THU was an issue when it hit the equate in models.py:

current_day = now.strftime('%a').upper()

I validated this in python 3.8 as well. Maybe those two days didn't translate from the Icelandic?

**Comment by Amondale** [comment]
I'd like to work on a fork based on this google API:

Maybe call gmaps API with lat/long to get current offset
https://maps.googleapis.com/maps/api/timezone/json?location=12.9716,77.5946&timestamp=1629304488&key=xxxxxxxx

which returns this JSON:
    {
        dstOffset: 0,
        rawOffset: 19800,
        status: "OK",
        timeZoneId: "Asia/Calcutta",
        timeZoneName: "India Standard Time"
    }

from which could be calculated real time open hours, based on lat/long and operating hours from the model. 

I tried the approach of adding this code to locations/models.py:

**Comment by allcaps** [comment]
The comment states that the _timezone is naive_.  To obtain the local time in the current time zone:
```
from django.utils import timezone
timezone.localtime(timezone.now())
```
I also think this code will render a string in your locale.
```
strftime('%a').upper()
```
That probably won't match the choice values:
```
DAY_CHOICES = (
    ("MON", "Monday"),
    ("TUES", "Tuesday"),
    ("WED", "Wednesday"),
    ("THUR", "Thursday"),
    ("FRI", "Friday"),
    ("SAT", "Saturday"),
    ("SUN", "Sunday"),
)
```
