### ISSUE TITLE
Reconcile Heroku deploy bits

### ISSUE THREAD

**Issue by daaray** [wagtail/bakerydemo#3]
The Heroku assets were hastily shoved in; we should review and ensure that it is set up well.

**Comment by daaray** [comment]
- [ ] Add support for S3 via django-storages for Heroku deployment

**Comment by heymonkeyriot** [comment]
This may be my lack of knowledge with Heroku and S3, but presumably the only way to implement it easily is with the [Heroku bucketeer](https://elements.heroku.com/addons/bucketeer)?

**Comment by heymonkeyriot** [comment]
Oh, I see you've flagged this on #27. Probably makes sense to have the conversation about S3 support there and we can close this ticket once the #26 PR has been merged in.
