### ISSUE TITLE
Clean up db migrations

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#30]
Just before release, let's squash all migrations one more time for a clean start, esp since we have many auto-named migration files.

**Comment by heymonkeyriot** [comment]
(sorry being an idiot with labels)

But yes. Completely agree. I also think we've got some conflicting merges around the place still.

**Comment by shacker** [comment]
Are we pretty confident that our models are stable at this point? If so, I'll do this tonight.

**Comment by heymonkeyriot** [comment]
Yes, I think we're at the point where our models are pretty stable. @shacker if you're happy to take it on that'd be awesome. Will be very happy to see the back of all the migrations 🎉

**Comment by heymonkeyriot** [comment]
Closed by PR #102
