### ISSUE TITLE
Docker-compose is specifying the Redis 3.0 image which is not available on ARM

### ISSUE THREAD

**Issue by kneckinator** [wagtail/bakerydemo#307]
Th result is that Docker is trying to run an x86 image on ARM (in my case Apple M1) which fails with `runtime: failed to create new OS thread (have 2 already; errno=22)` .

My proposed solution is to change this to use Redis 4.0 (or later) which has official ARM images.

I am not aware of any side-effects of making this change for the bakerydemo and can provide a PR for this change.

**Comment by juliat** [comment]
This would be great to have; I'm running into the same issue  with Redis 3.0

**Comment by thibaudcolas** [comment]
I see the file now says `redis:6.2` so I’ll assume this is no longer relevant.
