### ISSUE TITLE
Title in HomePage model should be not null

### ISSUE THREAD

**Issue by perastated** [wagtail/bakerydemo#308]
## Issue
Avoid using `null` on string-based fields such as CharField and TextField. 
If a string-based field has null=True, that means it has two possible values for `no data`: NULL, and the empty string.
* See: https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.Field.null

This is also followed in Wagtail, check this fix: https://github.com/wagtail/wagtail/commit/eb9cff7bf388735e988bfd9f084d7a5d34f0ba42

In this demo, I notice the following four fields violate this practice:
File: `/bakerydemo/base/models.py`
```python
class HomePage(Page):
    promo_title = models.CharField( null=True, )
  featured_section_1_title = models.CharField(null=True, )
  featured_section_2_title = models.CharField(null=True, )
  featured_section_3_title = models.CharField(null=True, )
```

## Fix
* Remove `null=True`. 
* Do relevant changes, like make the default be empty string.

**Comment by vihaanthora** [comment]
@perastated can I go ahead and fix this issue? Is there any need to assign this issue to me so that I can make the required Pull Request?
Thank You

**Comment by perastated** [comment]
Hi @vihaanthora, thanks for volunteering to fix it! 

I am not the maintainer of this repo, but please go ahead and submit the required PR as you want. 
You may find the instructions here: https://github.com/wagtail/bakerydemo/blob/master/contributing.md 

Probably we can also tag @gasman or @lb- to double-check and give advice on this issue/your PR.

**Comment by lb-** [comment]
Go for it @vihaanthora thanks
