### ISSUE TITLE
Location images being stretched to 100% on index page

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#31]
With:

`{% image location.image width-150 %}`

we get this:

<img width="721" alt="screenshot 2017-02-15 00 28 57" src="https://cloud.githubusercontent.com/assets/102694/22966163/cdf59eca-f315-11e6-9659-1a6741e9ca1c.png">

**Comment by heymonkeyriot** [comment]
I think @shacker we may be working on the same task since I'm looking at the styling and was starting with locations. The issue here is that the index page doesn't have any definition of rows or columns.

**Comment by shacker** [comment]
Yeah I started on it last night but then stopped when I realized the image stretching would prevent me from placing the thumbnails side by side. Just wanted to get the starter code in there. But yes, columns would solve this too.
