### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/bakerydemo#33]
The breadcrumb currently has fairly functional styling. Could stand to be improved.

There's also the open question of whether it's necessary. The benefit - from my perspective - is that it's a much easier way to understand how TreeBeard can be used than the main menu is (since the main menu is that much more complex). The negative is that - to accommodate it within the design - we're using `content-header`, `breadcrumb` and `content-body` as blocks rather than the more standard `content`.

**Comment by shacker** [comment]
I think it's important to keep breadcrumb - it's a common design pattern, solved elegantly by wagtail's hierarchical content. It shows off a key feature of WT.

**Comment by heymonkeyriot** [comment]
Cool. I think I have a solution in mind having had some conversations here. I'll try and do a PR tonight for review.

**Comment by heymonkeyriot** [comment]
With #53 merged in I think this can be closed.
