### ISSUE TITLE
the navbar on mobile version doesnt work

### ISSUE THREAD

**Issue by kentang2017** [wagtail/bakerydemo#348]
as title

**Comment by allcaps** [comment]
Works on my machine. Can you be more specific? What is "doesnt work"?

**Comment by Stormheg** [comment]
I've tested this with an iPhone running iOS 17 and Chrome on Android and it works like I expect it should.

Given this issue has been open for a year without more information, I'm going to close it as invalid.

If you are still experiencing this issue, please reply with more information as requested.
