### ISSUE TITLE
Accessibility issues reported through Pa11y testing

### ISSUE THREAD

**Issue by anujaraj** [wagtail/bakerydemo#356]
Automated Testing tool : Pa11y
Browser : Chrome
Operating System : Windows 11
Reproducing the issue : You can reproduce the issues using following steps

1.  Install node and pa11y
2.  Create a js file ( [[https://github.com/pa11y/pa11y](https://github.com/pa11y/pa11y)] )
3.  Run the bakery demo site
4.  Run the js file using `node <name_of_the_file>` on the command prompt
5.  Following issues would coulb be seen

Homepage (Search bar)
![Screenshot-1](https://user-images.githubusercontent.com/52713215/188303610-fddb3532-3f25-4e6a-9de0-eb8d3e644cd3.png)

Contact us 
![Screenshot (193)](https://user-images.githubusercontent.com/52713215/188303633-99b70793-0438-4507-b81d-6e753caccfa0.png)

NOTE : the urls used for testing bakerydemo were - homepage, breads, loactions, contact us, about, blog and gallery.

**Comment by thibaudcolas** [comment]
I believe this has all been fixed / I can’t reproduce the issues
