### ISSUE TITLE
Please update demo at bootstrap version 5

### ISSUE THREAD

**Issue by manyacz** [wagtail/bakerydemo#358]
Bootstrap v3.3.7  version so old.

**Comment by thibaudcolas** [comment]
Hi @manyacz, thanks for the suggestion but I don’t think this is a change we’d be interested in making at this stage.

This is a demo project for Wagtail, the front-end code is only there to help demonstrate the capabilities of Wagtail, and in my opinion Bootstrap is a bit of a distraction we shouldn’t even have on there to start with, considering the site has a very distinct visual identity.
