### ISSUE TITLE
Gallery Page

### ISSUE THREAD

**Issue by ArnarTumi** [wagtail/bakerydemo#36]
Needs to add link to first page that the image is used in, to show reverse linking from images to pages (I think I have seen this done sometime...)

**Comment by shacker** [comment]
@ArnarTumi I've renamed `choices` to `collection` and tweaked the display a bit. Do you think you'll have time to work on this linking? If not I'll take it.

**Comment by shacker** [comment]
Tracked it down - very cool. Had never noticed the `get_usage()` method on Image - apparently undocumented.

`	<a href="{{img_obj.image.get_usage.first.specific.url}}">`
