### ISSUE TITLE
referenced files that don't exist

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#37]
readme says:

`cp bakerydemo/settings/local.example.py bakerydemo/settings/local.py`

bash says:

`cp: bakerydemo/settings/local.example.py: No such file or directory`

and:

`./manage.py runserver` yields:

```
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

But secret key is already there in base.py. Is base.py no longer being read? Looks like `manage.py` now references:

`os.environ.setdefault("DJANGO_SETTINGS_MODULE", "bakerydemo.settings")`

But there is no `settings.py` in bakerydemo.  So I'm totally blocked and can't even runserver. Can't work on the project tonight. Grumble.

**Comment by shacker** [comment]
OK I see now that it should be `local.py.example` rather than `local.example.py` - fixing that gets everything going. 

But now I'm trying to figure out where my data went. A new initial migration was required, and when I log in, it's a fresh db without all of the initial content I've been saving up. Any idea what would have wiped my db and forced a fresh start? 

Might have to go to backup on this one.

**Comment by shacker** [comment]
Was able to successfully restore a copy of bakerydemodb from backup and am back in business. Still curious what wiped out that file, but moving on. Pushed a commit to fix the readme to reference the correct local.py.example.

**Comment by daaray** [comment]
Sorry about the dyslexic `cp` command.  If you root out the source of the wiped out db file, please do let me know.  I have not been able to recreate that.

**Comment by shacker** [comment]
@daaray Not sure exactly what commit changed this, but when trying to work with Tumi's old demo db just now, realized that at some point the location of the sqlite db file being looked for moved from docroot down into the bakerydemo dir. That change in code must have been what caused everything to reset for me last week. No worries, just following up.
