### ISSUE TITLE
Small typo in code snippet in local setup section of readme instructions 

### ISSUE THREAD

**Issue by salty-ivy** [wagtail/bakerydemo#391]
In documentation of setting up code base setup  in  `Setup with Virtualenv` section 
![image](https://user-images.githubusercontent.com/74553951/216814080-8d97e645-c730-46c5-ba28-fe4378f4da85.png)

command snippets have extra dollar signs, which makes them inconvenient to copy-paste

**Comment by laymonage** [comment]
I'd say this was intentional, rather than a typo. However, I do agree that the hassle caused by showing `$` isn't worth the small hint that they're shell commands. I'd rather remove the `$`s unless the copy button knows to strip them before putting the content to the clipboard.
