### ISSUE TITLE
Add development tooling - Ruff (linting)

### ISSUE THREAD

**Issue by lb-** [wagtail/bakerydemo#404]
It would be great to have the bakerydemo follow a code style guide, both for consistency in code and for this project being a demo of how to build a Wagtail project. 

It might be worth adding Ruff instead of Flake8 - see https://github.com/wagtail/wagtail/pull/10324

**Comment by laymonage** [comment]
We have Black as of #347 😃

**Comment by lb-** [comment]
Thanks @laymonage sorry - I double checked the requirements but only checked production requirements :|

**Comment by lb-** [comment]
Might close this actually, if Wagtail changes to Ruff we can re-open or revisit later.
