### ISSUE TITLE
Create a BasePage model and inherit

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#41]
Most of the main site sections include redundant image and introduction fields. Create a `BasePage` model to contain these and make Blog, Breads, Locations, Contact inherit from BasePage. Gallery is a special case. 

- [x] Blog
- [x] Breads
- [x] Locations

**Comment by daaray** [comment]
`Contact` does not have an `introduction` field; excluding that from the list.  However, the `GalleryPage` shares both fields, so I will add that to the list.
