### ISSUE TITLE
Delete rows from wagtailimages_rendition before exporting data

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#42]
Otherwise you end up with broken images in the admin.

**Comment by heymonkeyriot** [comment]
I suppose it doesn't really matter (since they'll be regenerated in the db) but would it not be easier to delete them in the fixtures file?

**Comment by shacker** [comment]
Not hugely different I suppose, but `delete from wagtailimages_rendition;` seems slightly easier. Either way; I'll experiment as needed.

**Comment by shacker** [comment]
@heymonkeyriot You're right, it makes more sense to do this in the data loader command so it doesn't get forgotten any  time we make a change. Added note to #10, closing this.
