### ISSUE TITLE
modelcluster. ValueError : invalid literal for int() with base 10: 'THU' on locations pages in the admin preview

### ISSUE THREAD

**Issue by leonh** [wagtail/bakerydemo#432]
On a fresh setup of the bakerydemo with Wagtail 5.0.1

I notice an error on the edit page for the "Location page" types in the preview section 

e.g.

Request Method: | GET
http://127.0.0.1:8000/locations/akranes/
exception type: ValueError
invalid literal for int() with base 10: 'THU'
Exception Location:  /Users/leon/envs/demos/wagtail/venv/lib/python3.11/site-packages/modelcluster/queryset.py, line 211, in test_day

**Comment by laymonage** [comment]
Thanks for reporting! I believe this is an instance of #wagtail/django-modelcluster#171, so I'm closing this as it's an issue with modelcluster rather than bakerydemo.
