### ISSUE TITLE
Documents in demo site

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/bakerydemo#440]
Follow-up to #175. We’d like one or two documents in the demo site’s content, so we can demonstrate and test the basics of how documents work in Wagtail. The documents don’t necessarily need a very bespoke integration – just having the files in the Documents library would be enough to support all we cover in our [guide documentation on documents](https://guide.wagtail.org/en-latest/how-to-guides/manage-documents/). Adding a document link in rich text would also be nice.

 Discussing this on Slack in #bakerydemo, there was interest for two options:

- Having a PDF related to the site being a demo on the "About" page
- Having a "here’s a similar recipe (PDF)" link on a recipe page

Personally I’m leaning towards the latter but open to alternatives.

## Recipes

Conveniently, our recipes come from Wikibooks, which already offer PDF exports of their content. Bottom left, "Download as PDF":

- https://en.wikibooks.org/wiki/Cookbook:Southern_Cornbread
- https://en.wikibooks.org/wiki/Cookbook:Hot_Cross_Bun
- https://en.wikibooks.org/wiki/Cookbook:Mincemeat_Tart

**Comment by Stormheg** [comment]
I've added two recipe pdf documents in https://github.com/wagtail/bakerydemo/pull/438
