### ISSUE TITLE
AttributeError: module 'dotenv' has no attribute 'read_dotenv'. Did you mean: 'load_dotenv'?

### ISSUE THREAD

**Issue by felp99** [wagtail/bakerydemo#467]
When doing the tutorial for running the first time I had this problem when running `./manage.py migrate`. The error come from two calls from the method `dotenv`:

- the first one in the `manage.py` file:
<img width="400" alt="image" src="https://github.com/wagtail/bakerydemo/assets/76445505/957c453b-c1b7-4eca-b26b-0f1a60f3616d">

- the second one in the `wsgi.py` file:
<img width="400" alt="image" src="https://github.com/wagtail/bakerydemo/assets/76445505/1ba7a324-347a-4489-a3e9-14475545b1a1">

Both are calling the method `dotenv.read_dotenv()` but it doesn’t work. For instance, it should be calling the method `.load_dotenv()` proposed in the error below.

<img width="400" alt="Screenshot 2023-11-28 at 14 42 47" src="https://github.com/wagtail/bakerydemo/assets/76445505/f12a3569-dbf7-4203-9673-ea2a365f241f">

**With the approve I can PR my changes with both methods being used dynamically.**

Versions:
- macOS Ventura: 13.5 (22G74)
- Chip Apple: M2
- Python: 3.11.4
- python-dotenv: 0.21.0

**Comment by gasman** [comment]
To clarify, this is with [bakerydemo](https://github.com/wagtail/bakerydemo/), rather than [the tutorial](https://docs.wagtail.org/en/stable/getting_started/tutorial.html)?

Bakerydemo [uses django-dotenv](https://github.com/wagtail/bakerydemo/blob/cd0910420313e0f18c6b9c2a048b227f1f8b3296/requirements/base.txt#L2), not python-dotenv.

**Comment by felp99** [comment]
Even following the tutorial I receive the same error. We should implement an exit for those one's who the computer don't see the write path for dotenv, let me do the PR

**Comment by gasman** [comment]
All of the setup instructions for bakerydemo tell you to start from a clean virtualenv, or use an isolated VM or container. If you're following the instructions as directed, python-dotenv will never be part of the environment, unless I'm missing something?
