### ISSUE TITLE
Fix all remaining design and coding accessibility issues

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/bakerydemo#493]
Follow-up to [wagtail#12157](https://github.com/wagtail/wagtail/issues/12157). We want the bakerydemo website to be free of design and coding related accessibility issues. Content issues are desirable so we can test the accessibility checker.

- [x] Fix color contrast / link not distinguishable in text issues showing up on recipe pages
- [x] Fix main navigation menu issues when a top-level menu item has sub pages configured to show in the menu (create a page as a child of "Contact us"). Or remove support for dropdown menus
- [x] (test all other pages of the site and report possible improvements here / fix the issues)

**Comment by albinazs** [comment]
**Fixed issues:**

[x] Fix color contrast and link not distinguishable in text issues showing up on Recipe pages
[x] Remove support for dropdown menus within the main navigation menu
[x] Fix the aria-allowed attributes issue on the Contact us form page
[x] Fix the missing table headers issue on the Breads index page
[x] Fix the missing heading level 1 issue on the Recipes index page
[x] Add missing headings to the Location pages
[x] Update Twitter to X on the FE only (icon, label, field verbose name for admin)

**Other possible improvements:** 

[] Add a skip main navigation link
[] Fix not visible focus appearance for the `.picture-card` (used for blog items on the home page, location items on the location index page)

**Comment by albinazs** [comment]
**Additional fixed issue:**

[x] Add a skip main navigation link
