### ISSUE TITLE
Bring in bread images

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#5]

**Comment by shacker** [comment]
@ArnarTumi Can you refresh my memory on how this worked / what the game plan is? We were going to put all site images into a .zip file included in the repo, right? And was there a management command that was going to unzip that, move them into `media/original_images`, and then loads the `images.json` fixture file to reference those same images?

I have the json file, but I don't have the .zip file - can you send it to me please?

**Comment by ArnarTumi** [comment]
We decided on not putting the images into the repo for now as it would make the repo so much bigger. We could revisit that thought at some point, after I ran the originals through tinyjpg the images are only 4mb total, and thus could probably just be added to the repo...
Anyway, attached are the images, you can grab a copy of my sqlite db from the slack chat, that should get you up and running with the images attached and all the "Breads" pages included
[Breads.zip](https://github.com/wagtail/bakerydemo/files/779457/Breads.zip)

**Comment by shacker** [comment]
All BreadPages are now in (my local, not committed). Partially automated, partially manual. Styling work for breads index and detail needed - separate ticket for that. 

Thanks for the yeoman's work on this @ArnarTumi !
