### ISSUE TITLE
Location styling missing styles?

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#51]
After merging https://github.com/wagtail/bakerydemo/pull/32 , location page for me is styled as shown, not as screenshot in the PR. Missing CSS? 

<img width="817" alt="screenshot 2017-02-19 00 45 57" src="https://cloud.githubusercontent.com/assets/102694/23100725/0e036ba8-f63d-11e6-83a3-2e4a3851d6ac.png">

**Comment by heymonkeyriot** [comment]
It would appear that the way that you merged this in to master caused a lot of the work to be lost, which I think includes the styling because the various classes on the HTML have been removed. Will re-create a PR with that taken out.

**Comment by heymonkeyriot** [comment]
D'oh! Looking a second time I think it's the PR on the operating hours from @daaray that knocked out the styling :)

The pull request #53 should have put everything back in the correct place.

**Comment by shacker** [comment]
Ah. Yeah it merged very cleanly, and I only had one small conflict to resolve that was not style related. I'll look at PR #53 .
