### ISSUE TITLE
Replace Twitter link with Mastodon link

### ISSUE THREAD

**Issue by laymonage** [wagtail/bakerydemo#511]
Wagtail has decided to move away from Twitter/X to Mastodon (specifically Fostodon):

- https://x.com/WagtailCMS/status/1834237886285103507
- https://fosstodon.org/@wagtail

We need to change the following:
- Use Mastodon logo https://github.com/wagtail/bakerydemo/blob/d72c386436a7412340a694397205377708a6d722/bakerydemo/templates/includes/footer.html#L16-L22
- And perhaps change the settings field to something like `mastodon_url`: https://github.com/wagtail/bakerydemo/blob/d72c386436a7412340a694397205377708a6d722/bakerydemo/base/models.py#L487-L489

**Comment by lb-** [comment]
Implemented in https://github.com/wagtail/bakerydemo/pull/512

**Comment by Vishal-Prajapati17** [comment]
Can I work on this issue ?
