### ISSUE TITLE
Remove `from __future__ import unicode_literals`

### ISSUE THREAD

**Issue by lb-** [wagtail/bakerydemo#518]
I think we can now remove the `from __future__ import unicode_literals` declarations in a few files as we are now fully migrated to Python 3.*  (and no longer support older versions of Python in Wagtail).

https://github.com/search?q=repo%3Awagtail%2Fbakerydemo%20from%20__future__%20import%20unicode_literals&type=code

See 
- https://python-future.org/unicode_literals.html
- https://docs.python.org/3/library/__future__.html

**Comment by input** [comment]
Hi @lb-
I'll do this as a first issue.

**Comment by lb-** [comment]
Thanks @input - nice username by the way, how did you snag that?

**Comment by input** [comment]
Thanks - signed up a long time ago 😄
