### ISSUE TITLE
Handle locations on About template, or ditch that relationship

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#54]
Locations are shown as children of `LocationIndex`. About also has `AboutLocationRelationship`, which lets you manually attach those same locations to the about page. But if you do, they don't show up since the template doesn't handle them. 

Either add that handling to the about template, or remove the `AboutLocationRelationship` since it duplicates data on Locations and we're going to use About for info about  the demo itself anyway.

**Comment by heymonkeyriot** [comment]
I think we should drop the relationship. We show in the demo how this type of demo can be set up between `People` in the base app, and `BlogPage` in the blog app. I think given the copy you've shared on #4 works well, and having the location relationship there will just confuse the issue. If we change our mind we can always put it back in again.
