### ISSUE TITLE
Homepage styling and content

### ISSUE THREAD

**Issue by heymonkeyriot** [wagtail/bakerydemo#58]
I think the issue between styling of the homepage and the content it has is quite interlinked. We didn't, in the sprint, have time to really have a conversation about what should be on the homepage. A little like the about page it'll need to juggle - in my mind - the content model of the bakery chain, alongside being clear it's a demo for Wagtail.

Alongside any homepage fields we have the following apps we can show content from:

 - About page
 - Blog page
 - Bread page
 - Locations
 - Gallery

I wonder whether we could have a content model similar to a shop/ chain, though the first screen the user sees is relevant to Wagtail rather than the bakery? For the sort of creative positioning I had in mind: 

 - http://www.traderjoes.com/
 - http://www.planetorganic.com/
 - https://www.riverford.co.uk/

Happy to draw something up if useful? But was also curious to hear what others had thought.

**Comment by shacker** [comment]
My personal vote would be to keep it short and simple, probably just a single StreamField with no data integrations. Willing to be outvoted on this.

**Comment by heymonkeyriot** [comment]
My concern about it being a StreamField element is that it might be a little difficult to style. If we're going to keep it simple I'd suggest we at least keep it field based. I'll try and think of something a little more concrete to propose than my admittedly vague opening post above.

**Comment by shacker** [comment]
Classic title and either RichTextField or TextField body would be fine too.

**Comment by shacker** [comment]
For reference: Ben's original design: 
http://playground.torchboxapps.com/bakery-html-proto/standard.html

**Comment by heymonkeyriot** [comment]
That was actually Ben's design for the blog page/ streamfield elements. The design for the homepage (which wasn't really completed, and based on the proposal from @tomdyson) is at http://playground.torchboxapps.com/bakery-html-proto/

**Comment by shacker** [comment]
Ah! I missed that somehow, seeing now for the first time. Good timing, I was about to load up dummy homepage content. What do you think - do you want to keep this "departure" look and feel? Or stick with a streamfield with dummy content for the hp? I think we definitely want a hero image for it. If we keep Ben's design, what's the best way to model - a new HomePageSection model for the subheads and their texts?

**Comment by heymonkeyriot** [comment]
I'd like to stick closer to the proposal from @tomdyson and @benenright for sure. I think trying to keep it within a StreamField will be quite limiting, and won't have that eye-catching aspect that I think we're hoping for.

Is there a reason to use a model rather than fields? I was thinking to use a multiFieldPanel that contained an image field, a subhead field and a text field that were contained within the HomePage model itself. Do you think that would work?

**Comment by shacker** [comment]
Yes, good plan. I like it. I'll work on this tonight (unless you're available sooner).

**Comment by heymonkeyriot** [comment]
Ah sorry I had started during my lunch break today. I've just pushed the model updates that allow us to fit in with the design suggested by Ben alongside some additional bits that I think would be cool. I have this evening to work on it so hopefully will have something to share in a few hours.

**Comment by shacker** [comment]
@heymonkeyriot Ready to close this?

**Comment by heymonkeyriot** [comment]
Absolutely. I'd left it open because of the word "content" in the subject, but agreed that we should simply close it off.
