### ISSUE TITLE
Demonstrate ManyToMany

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#64]
Wagtail 1.9 now supports true ManyToMany relations. This is a pretty big deal and erases a long-standing limitation. I know it's late in the game but can we think of a way to demonstrate this important feature?

**Comment by daaray** [comment]
Bread <-> Ingredients seems like the obvious one?

**Comment by heymonkeyriot** [comment]
I think we should definitely demo it. Bread <-> ingredients seems like a good one.

**Comment by shacker** [comment]
Agreed, ingredients is a natural fit. Flour everywhere...

Anyone want to take this?

**Comment by daaray** [comment]
I can get to it this evening.  If someone wants to before then, feel free to re-assign.
